Repository sriganeshres/WorkHub-Pro, pull requests merged in 2024-04, with the labels that each got.

#19 Added the create Organisation screen
  Backend/models/users.go
  app/src/main/java/com/work/workhubpro/api/UserApi.kt
  app/src/main/java/com/work/workhubpro/models/Organisation.kt
  app/src/main/java/com/work/workhubpro/models/User.kt
  app/src/main/java/com/work/workhubpro/repository/OrganisationCreation.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navigation.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navscreen.kt
  app/src/main/java/com/work/workhubpro/ui/screens/createOrg/CreateOrganisationViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/createOrg/createOrg.kt
  app/src/main/java/com/work/workhubpro/ui/screens/landing/landingPage.kt
  app/src/main/java/com/work/workhubpro/ui/screens/landing/landingViewModel.kt
  app/src/main/res/drawable/admin_symbol.png
  app/src/main/res/drawable/company_symbol.png
  app/src/main/res/drawable/img_2.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement

#24 LoginPage added
  app/src/main/java/com/work/workhubpro/api/UserApi.kt
  app/src/main/java/com/work/workhubpro/repository/LoginRepo.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navigation.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navscreen.kt
  app/src/main/java/com/work/workhubpro/ui/screens/landing/LandingPage.kt
  app/src/main/java/com/work/workhubpro/ui/screens/loginPage/LoginPage.kt
  app/src/main/java/com/work/workhubpro/ui/screens/loginPage/LoginPageViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#30 Removed Project_service folder
  Backend/Projects_service/api/handlers.go
  Backend/Projects_service/api/middleware.go
  Backend/Projects_service/api/routes.go
  Backend/Projects_service/cmd/main.go
  Backend/Projects_service/database/db.go
  Backend/Projects_service/utils/utils.go
Labels: bugfix

#31 Added tasks model and its services
  Backend/.gitignore
  Backend/Workhub_service/api/handlers.go
  Backend/Workhub_service/api/routes.go
  Backend/Workhub_service/database/db.go
  Backend/models/projectmodel.go
  Backend/models/tasks.go
  Backend/models/users.go
Labels: enhancement

#35 Added Projects Page and fixed internal issues
  app/src/main/java/com/work/workhubpro/SharedViewModel.kt
  app/src/main/java/com/work/workhubpro/api/WorkHubApi.kt
  app/src/main/java/com/work/workhubpro/models/Project.kt
  app/src/main/java/com/work/workhubpro/models/Task.kt
  app/src/main/java/com/work/workhubpro/repository/Projectcreation.kt
  app/src/main/java/com/work/workhubpro/repository/TaskCreation.kt
  app/src/main/java/com/work/workhubpro/repository/TaskRepository.kt
  app/src/main/java/com/work/workhubpro/ui/screens/bottombar/Bottombar.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projectDetails/ProjectDetailsViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projectDetails/projectDetails.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projects/ProjectsList.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projects/ProjectsListViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/taskform/TaskFormViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/taskform/taskform.kt
Labels: enhancement, feature
