Repository sriganeshres/WorkHub-Pro, pull requests merged in 2024-03, with the labels that each got.

#6 Adding the Signup Feature
  Backend/.gitignore
  Backend/Authentication_service/api/handlers.go
  Backend/Authentication_service/api/middleware.go
  Backend/Authentication_service/api/routes.go
  Backend/Authentication_service/cmd/main.go
  Backend/Authentication_service/database/db.go
  Backend/Authentication_service/database/models.go
  Backend/Authentication_service/utils/utils.go
  Backend/Makefile
Labels: feature

#8 Fixes #5
  README.md
Labels: documentation

#9 Added env example
  Backend/.env.example
Labels: enhancement, feature

#13 Bugs are removed
  Backend/Authentication_service/api/handlers.go
  Backend/Authentication_service/main.go
  Backend/go.mod
  Backend/go.sum
  app/src/main/java/com/work/workhubpro/WorkActivity.kt
  app/src/main/java/com/work/workhubpro/ui/composables/TextFiledComposables.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navigation.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Bottombar.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Bottombar/Bottombar.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Community.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Home.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Home/Home.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Profile.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Projects.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Signup/SignupScreen.kt
  app/src/main/java/com/work/workhubpro/ui/screens/SignupScreen.kt
Labels: feature

#15 Redefined Signup
  Backend/Authentication_service/api/handlers.go
  Backend/Authentication_service/cmd/main.go
  Backend/Authentication_service/database/db.go
  Backend/Makefile
Labels: bugfix

#18 Refactoring and Made models global and added Login
  .idea/vcs.xml
  Backend/Authentication_service/api/handlers.go
  Backend/Authentication_service/database/db.go
  Backend/Authentication_service/utils/utils.go
  Backend/Makefile
  Backend/models/Workhub.go
  Backend/models/projectmodel.go
  Backend/models/users.go
  app/src/main/java/com/work/workhubpro/ERPActivity.kt
  app/src/main/java/com/work/workhubpro/MainActivity.kt
  app/src/main/java/com/work/workhubpro/api/UserApi.kt
  app/src/main/java/com/work/workhubpro/di/NetworkModule.kt
  app/src/main/java/com/work/workhubpro/models/User.kt
  app/src/main/java/com/work/workhubpro/repository/UserRepository.kt
  app/src/main/java/com/work/workhubpro/ui/composables/TextComposables.kt
  app/src/main/java/com/work/workhubpro/ui/composables/TextFiledComposables.kt
  app/src/main/java/com/work/workhubpro/ui/navigation/Navigation.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Bottombar/BottomViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Community/CommunityViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Home/HomeViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Profile/ProfileViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/Projects/ProjectViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/bottombar/BottomViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/bottombar/Bottombar.kt
  app/src/main/java/com/work/workhubpro/ui/screens/community/Community.kt
  app/src/main/java/com/work/workhubpro/ui/screens/community/CommunityViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/home/Home.kt
  app/src/main/java/com/work/workhubpro/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/profile/Profile.kt
  app/src/main/java/com/work/workhubpro/ui/screens/profile/ProfileViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projects/ProjectViewModel.kt
  app/src/main/java/com/work/workhubpro/ui/screens/projects/Projects.kt
  app/src/main/java/com/work/workhubpro/ui/screens/signup/SignupScreen.kt
  app/src/main/java/com/work/workhubpro/ui/screens/signup/SignupViewModel.kt
Labels: enhancement
